config/routes.rb
Rails.application.routes.draw do
  resources :pages
  root to: "home#index"

  resources :types
  resources :abilities
  resources :regions
  resources :pokemons do
    collection do
      get "search"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/common/_footer.html.erb
<%= link_to "Home", root_path, class: "navbar-item" %>
<%= link_to "Pokémons", pokemons_path, class: "navbar-item" %>
<%= link_to "Regions", regions_path, class: "navbar-item" %>
<%= link_to "Types", types_path, class: "navbar-item" %>
<%= link_to "Abilities", abilities_path, class: "navbar-item" %>
<% cms_pages.each do |page| %>
    <%= link_to page.title, page_path(page), class: "navbar-item" %>
<% end %>

app/views/common/_nav.html.erb
<nav class="navbar">
  <div class="navbar-menu">
    <%= form_with(url: search_pokemons_path, method: :get, local: true, class: "navbar-item") do %>
      <%= text_field_tag(:keywords, nil, placeholder: "Search for Pokémons", class: "input") %>
      <%= submit_tag("Search", class: "button") %>
    <% end %>
  </div>
  <div class="navbar-end">
    <%= render partial: "common/footer" %>
  </div>
</nav>